---
title: "Exploring Urban Data with Machine Learning "
---
<style>
@import url('https://fonts.googleapis.com/css?family=Noto+Sans|VT323');

body{
  font-family: 'Noto Sans', sans-serif;
  font-size: 12px;
  line-height: 24px;
}

h1,h2,h3,h4 {
  font-family: 'VT323', monospace;
}

#navbar {
  font-family: 'VT323', monospace;
  font-size: 18px;
}

.container { width: 1000px; }


g-table-intro h4 {
  text-indent: 0px;
}
</style>

### Instructor: Kaz Sakamoto
### Spring 2019 Tuesday 7-9 pm Fayerweather 200 (session B)

------

## Course Background

Machine learning has become increasingly accessible for anyone with a statistical bent and a penchant for writing code. Predicative analytics are being utilized by academia, government, and business to gain insights from their data. We live in a data rich world where leveraging automation drives decision making at a greater and greater pace. Students will explore urban data through a computational framework and immerse themselves with fundamental skills necessary for today's technological landscape.

R has become a go-to programming language for data scientist packed with helpful libraries and functions to shape and transform data. One of the many reasons why data scientists love using the R language is that it’s open sourced, where you are free to use it and it comes with an active community continually adding resources.

## Course Objectives

This class will be an introduction to machine learning techniques. The course will require a basic understanding of statistical concepts and coding skills. The course will not go into every detail of each technique but will provide further reading and there will be class discussions to stimulate ideas.

The first portion of the class will be dedicated to learning the basics of R especially around shaping data for machine learning purposes. The second portion of the class will be working with algorithms. Some of the machine learning tasks the class will explore are classification and regression algorithms. The techniques we will cover include, random forests, gradient boosting machines, and linear regression.

The class will work on tuning parameters and evaluating performance of models. A diverse selection of urban data sets will be used in the class; some of them include 311 data, PLUTO, US census, and Citi bike data.

The final project will be a InClass Kaggle competition testing student's skills gained during class, accompanied by a report. 
