---
title: "Syllabus"
---

--------

## Course Description

Urban planning decisions are inherently difficult, as cities comprise systems of immense complexity and increasing volumes of data. While planners aren’t new to quantitative tools to model decision-making, this course will engage the role of technologies in the planning process by focusing on the challenges and advantages gained from three new skills: data munging, data visualization, and machine learning. Students will learn to apply these skills and techniques to describe, model, and evaluate their results alongside the history and theory intersecting technocracy and urban planning.

## Course Goals

The objective of this course is to expose urban planning students to the world of Data Science. Future urban planners will be required to handle vast quantities of data that governments and companies are amassing. This data will not only vary in quality and variety, but planners must also wield methods to clean and merge data into a usable state. Once the data is cleaned, machine learning algorithms will help find hidden insights, automate decision-making, and plan the future of cities. Throughout the course, readings and discussions will engage students on critical topics ranging: objectivity through quantification, the role of planners in data science, and modern technological culture against the city. 

## Learning Objectives

By the end of the semester, students should be able to: 
- Be proficient at Data Munging
- Run through EDA
- Apply and execute the correct ML algorithm
- Evaluate the results
- Communicate methods and modeling results clearly

## Course Expectations

### Attendance

Classroom attendance is mandatory for this class. We expect an e-mail or in-person explanation on any absences at least 24 hours before class. You will be responsible to catch up on class materials by yourself and your classmate’s help, and are expected to complete assignments at the same deadline as the rest of your class.

## Resources

### Text Books

**R for Everyone: Advanced Analytics and Graphics** by *Jared Lander* ([amazon](https://www.amazon.com/Everyone-Advanced-Analytics-Graphics-Addison-Wesley/dp/013454692X/ref=sr_1_1?ie=UTF8&qid=1518561244&sr=8-1&keywords=r+for+everyone))

**R for Data Science** by *Hadley Wickhham*
([Online](https://r4ds.had.co.nz/))

**Applied Predictive Modeling** by *Max Kuhn and Kjell Johnson*
([Online](https://link-springer-com.ezproxy.cul.columbia.edu/book/10.1007%2F978-1-4614-6849-3))

**Text Mining with R** by *Julia Silge and David Robinson*
([Online](https://www.tidytextmining.com/))


### Online Resources

[Online Stat Book](http://onlinestatbook.com/2/index.html) -Basic stats knowledge

### Assignments

There will be weekly [assignments](assignments.html), consisting of problem sets and reading responses that reinforce and propel topics covered in class.

### Late Assignments

Assignments will be deducted 10% for assignments up to a day late, 50%  between 2-7 days and assignments later than a week will not be accepted. 

### Readings

There will also be bi-weekly [readings](readings.html) assigned.

### Final Deliverable

The end of the class will be accompanied by a 311 categorization challenge and report. The final report will document data/methods, including commented code, description of analysis, and conclusions. 

### Grading

* Problem Sets 40%
* Reading Responses 20%
* Final Report 40%

## GSAPP Honor System and Plagiarism 

Students must adhere to the principles of [academic honesty](https://www.arch.columbia.edu/honor-system) and ensure that all work submitted is fully theirs and adhere to the [GSAPP Plagarism Policy](https://www.arch.columbia.edu/plagiarism-policy) set forth. Students found guilty of plagiarism or academic dishonesty will be subject to appropriate disciplinary action.

## Topics

### R Basics

* Getting started with R
* R Environment - intro to RStudio
* Essential R Programming
* Packages
* Data Types
* Data Structure
* Functions
* Logical Operators

### Working with Data

* Data Munging
* Simple Web Scraping
* Reading in Data
* Grep (regular expressions)
* Dplyr
* Reshape
* Missing Data
* Exploratory Data Analysis
* Getting started with ggplot2
* Histograms and Distributions
* R Markdown

### Machine Learning

* What is machine learning?
* Machine learning problems
* Supervised Learning
* Regression, Classification
* Classification
    + KNN K nearest neighbors
    + KNN exercise 
    + Naive Bayes 
    + Decision Trees
    + Decision tree exercise
* Regression
    + Generalized linear models
    + GLM exercise 
    + Regression with trees
    + Regression trees exercise
* Unsupervised Learning
* Clustering
    + K-means
    + Hierarchical Clustering
* Time series Modeling
    + Autoregression
    + ARIMA
    + SARIMA
    + ETS
* Advanced Models
    + Random Forests
    + SVM
    + Elastic Net
* Model Evaluation
    + Confusion matrix
    + Sensitivity, specificity, precision, recall
    + ROC curves
    + Residuals
    + P-value
    + RMSE
    + Cross Validation


--------

# Calendar

### Week 1 - 1/22/2019
**Objective**

By the end of this class, students should be able to...

- Be familiar with computational thinking
- Distinguish the difference between machine learning and Artificial Intelligence?
- Be exposed to machine learning applications
- Work with basic data types and variables in R

**Class Plan**

- Lab - Intro to R part 1

**Reading**

- The Rise of Statistical Thinking | Porter

**Assignment**

- Assignment 1 - Intro R
- Reading Response 1

### Week 2 - 1/29/2019
**Objective**

By the end of this class, students should be able to...

- Discuss the pervasiveness of statistics in business and academia
- Explore causality in the social sciences
- Work with data structures and functions in R

**Class Plan**

- Reading discussion
- Lab - Intro to R part 2

**Assignment**

- Assignment 2 - Functions

### Week 3 - 2/5/2019
**Objective**

By the end of this class, students should be able to...

- Work with APIs to pull data
- Read in data from multiple sources
- Explain the concept of "Tidy Data"
- Be exposed to common data cleaning and manipulation techniques

**Class Plan**

- Lab - Data Munging 3

**Reading**

- Trust in Numbers & Rethinking Objectivity | Porter & Megill

**Assignment**

- Assignment 3 - Data Munging
- Reading Response 2 

### Week 4 - 2/12/2019
**Objective**

By the end of this class, students should be able to...

- Critically examine quantification and objectivity
- Discuss the rise of the scientific method and standardization in society
- Describe the philosophy of Exploratory Data Analysis (EDA)
- Practice common EDA techniques
- Utilize R Markdown to make data-driven documents

**Class Plan**

- Reading discussion
- Lab - Reports with R Markdown 4

**Assignment**

-Assignment 4 - EDA/Reports

### Week 5 - 2/19/2019
**Objective**

By the end of this class, students should be able to...

- Implement simple linear regression
- Discuss the theory and methods behind regression
- Visualize and interpret the results from simple linear regression

**Class Plan**

- Lab - Linear Regression 5

**Reading**

- Critical Theory of Technology | Feenberg

**Assignment**

- Assignment 4 - Linear Regression
- Reading Response 3 

### Week 6 - 2/26/2019
**Objective**

By the end of this class, students should be able to...

- Critically examine technology through the instrumentalist substantive theories
- Apply theories of technology to AI and ML
- Explore the production and control of technology
- Implement multiple linear regression and logistic regression
- Continue exploring the methods behind regression analysis
- Visualize and interpret the results from more complex regression modeling


**Class Plan**

- Reading discussion
- Lab - Mulitvariate Regression +  Generalized Linear Models 6

**Assignment**

- Assignment 5 - Mulitvariate Regression +  Generalized Linear Models

### Week 7 - 3/5/2019
**Objective**

By the end of this class, students should be able to...

- Be familiar with time series data
- Classify patterns in time series data
- Implement and explain various models for forecasting

**Class Plan**

- Lab - Forecasting 7

**Reading**

- Reading - Making Social Science Matter | Flyvbjerg

**Assignment**

- Assignment 6- Forecasting
- Reading Response 4


### Week 8 - 3/12/2019
**Objective**

By the end of this class, students should be able to...

- Engage in discourse of the role rationality has on social science research
- Question the role of the scientific method in the social sciences
- Explain classification in the context of machine learning
- Visualize and interpret the results from classification modeling

**Class Plan**

- Reading discussion
- Lab - Classification 8

**Assignment**

- Assignment 7 - Classification

### Week 9 - 3/19/2019 
**Spring Break**

### Week 10 - 3/26/2019
**Objective**

By the end of this class, students should be able to...

- Explain the components that make up natural language processing(NLP)
- Ingest and handle various text inputs
- Create tidy text for text mining applications
- Visualize and interpret NLP results

**Class Plan**

- Lab - Natural Language Processing 10

**Reading**

-  Order without Design | Bertaud

**Assignment**

- Assignment 9 - Natural Language Processing
- Reading Response 5

### Week 11 - 4/2/2019
**Objective**

By the end of this class, students should be able to...

- Contrast the approaches of urban economics and urban planning
- Explore the effects of the market and regulations in city design
- Identify objectivity in the urban realm
- Apply unsupervised learning algorithms such as k-means and hierarchical clustering
- Visualize and interpret clustering results
- Discuss final project topics and ideas

**Class Plan**

- Reading discussion
- Lab 11 - Unsupervised Learning

**Assignment**

- Assignment 10 - Final Project Scoping + Data (due in two weeks)

### Week 12 - 4/9/2019
**Objective**

By the end of this class, students should be able to...

- Load and display spatial data
- Perform various geoprocressing methods
- Execute geocomputational workflows

**Class Plan**

- Lab 12 - Geospatial

**Reading**

- Weapons of Math Destruction | O'Neill

**Assignment**

- Reading Response 6

### Week 13 - 4/16/2019
**Objective**

By the end of this class, students should be able to...

- Discuss possible adverse effects of deploying machine learning algorithms
- Argue instances where algorithms should or should not be used
- Comprehend the variance-bias trade off
- Explore regularization through the Lasso and Ridge methods

**Class Plan**

- Reading discussion
- Lab 13 - Regularization

**Assignment**

- Final Project

### Week 14 - 4/23/2019
**Objective**

By the end of this class, students should be able to...

- Implement algorithms and tune parameters with Caret
- Explain boosting and bagging in the context of ML
- Perform more complex algorithms such as random forest and XGBoost
- Visualize and interpret the results from XGBoost

**Class Plan**

- Lab 14 - Hyperparameter Tuning

**Assignment**

- Final Project

### Week 15 - 4/30/2019
**Work day**

### Week 16 - 5/6/2019
**Final Report Due**

