---
title: "Assignment 5"
author: "Kaz Sakamoto"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE, warning = FALSE, error = FALSE)
```

In this assignment we will be continue working with Rmarkdown and R. Please submit a html document as your submission. Title should be Lastname_Firstname_assignment5.html and submit to canvas.

Create an rmarkdown document that will output html. Don't forget to fill out the yaml with your title, author, and date.

For each task use a `#` and make sure your code and output get returned.


## Task 1

Read in nycSales.csv. (in the files folder on canvas)

## Task 2

Do some EDA

Explain what you see.

## Task 3

clean up any columns that need to be munged, ex. `num_beds`, or if you want to change `amenities_list` or `transit_list` into predictors.

## Task 4

create a multiple regression with price as your response variable and predictor variables of your choosing.

Explain your results with `summary` and `coefplot`.

