---
title: "Assignment 8"
author: "Kaz Sakamoto"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE, warning = FALSE, error = FALSE)
```


## K-means

I would like you to take the same PLUTO csv of Manhattan from the last assignment and we are going to see clustering of lots with the fields Assessed Total Value, Lot Area, and Building Area. Please play around with scale number of K values with your K-means to see if you can make sense of the data. We know that there are different land use schemes that could be a good way to see clusters. Please share the code and have some visual outputs too.

## KNN

I would also like to use this data to do some KNN classification too. I would like you to first break up your data by Multifamily Elevator or Industrial/Manufacturing lots (landuse), and set the seed for 1234 and a train test split of 70/30 percent. Play with different variables and number of Ks to find a solution that can get you pretty good predictions. Again share the code and have some visual outputs too.