---
title: "Assignment 2"
author: "Kaz Sakamoto"
output: html_document
---
    
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE, warning = FALSE, error = FALSE)
```

In this assignment we will be continue working with R. Please submit a rscript (.r file) with your submission. Title should be Lastname_Firstname_assignment2.r and submit to canvas. Also give step-by-step code for credit.


## Task 1

Create your own function mean_N to calculate the mean of vector of numbers

## Task 2

Create your own function median_N to calculate the median of a vector of numbers

## Task 3

Create your own function range_N to return the range of a vector (should be a vector of two numbers)

## Task 4

Create a function called sum_N that removes na values and uses a for each to loop through each item in a vector to add up each elemtn in a vector(don't use the sum function that's already built).

## Task 5

Create a function called skipFunc that takes in two arguments, a vector and a character. If the character is "even", I want the function to remove all the even numbers and return the odd numbers. If the character is "odd", I want the function to remove all the odd numbers and return the even numbers.