---
title: "Assignment 4"
author: "Kaz Sakamoto"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE, warning = FALSE, error = FALSE)
```

In this assignment we will be continue working with Rmarkdown and R. Please submit a html document as your submission. Title should be Lastname_Firstname_assignment4.html and submit to canvas.

Create an rmarkdown document that will output html. Don't forget to fill out the yaml with your title, author, and date.

For each task use a `#` and make sure your code and output get returned.


## Task 1

Read in who_registeredVehicles.csv, world_countries.csv, who_trafficDeaths.csv. (in the files folder on canvas)

Join world_countries.csv with who_registeredVehicles.csv and who_trafficDeaths.csv save this object as `df`

## Task 2

Create a histogram of the `Estimated road traffic death rate (per 100 000 population)`

Explain what you see.

## Task 3

Create a histogram of the `Number of registered vehicles` with a colors corresponding to `Continent`

Explain what you see.

## Task 4

Create a scatterplot of the `Estimated road traffic death rate (per 100 000 population)` on the y axis and `Number of registered vehicles` on the x axis.

Explain what you see.


## Task 5

create a facet_wrap of scater plots of the `Estimated road traffic death rate (per 100 000 population)` on the y axis and `Number of registered vehicles` on the x axis. The wrap should be on `Continent`.

Explain what you see.